version: '3'
services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grc
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
  #test:
   # image: alpine
   # command: sh -c "apk add --no-cache bind-tools netcat-openbsd && tail -f /dev/null"
    #networks:
     # - app-network
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    networks:
      - app-network
    command:
      - start-dev
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=12345678
      - DB_VENDOR = postgres
      - DB_ADDR = db
      - DB_DATABASE=grc
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_SCHEMA= public
      - JDBC_PARAMS="useSSL=false&allowPublicKeyRetrieval=true"
      - KEYCLOAK_LOGLEVEL=DEBUG
    ports:
      - 8080:8080
    depends_on:
      - db 
 
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
